version: "3.7"
services:
  nginx:
    container_name: some-nginx
    image: nginx
    restart: always
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - timeline1
      - timeline2
      - timeline3
      - timeline4
      - timeline5
      - timeline6
  timeline1:
    image: timeline
    container_name: timeline1
    expose:
      - "8080"
    entrypoint: ["/bin/bash", "build.sh"]

  timeline2:
    image: timeline
    container_name: timeline2
    expose:
      - "8080"
    entrypoint: ["/bin/bash", "build.sh"]

  timeline3:
    image: timeline
    container_name: timeline3
    expose:
      - "8080"
    entrypoint: ["/bin/bash", "build.sh"]

  timeline4:
    image: timeline
    container_name: timeline4
    expose:
      - "8080"
    entrypoint: ["/bin/bash", "build.sh"]
  timeline5:
    image: timeline
    container_name: timeline5
    expose:
      - "8080"
    entrypoint: ["/bin/bash", "build.sh"]
  timeline6:
    image: timeline
    container_name: timeline6
    expose:
      - "8080"
    entrypoint: ["/bin/bash", "build.sh"]