version: "3.7"
services:
  nginx:
    container_name: some-nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    #   - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - timeline1
      - timeline2
      - timeline3
  timeline1:
    image: timeline
    container_name: timeline1
    expose:
      - "8080"
    entrypoint: ["/bin/bash", "build.sh"]

  timeline2:
    image: timeline
    container_name: timeline2
    expose:
      - "8080"
    entrypoint: ["/bin/bash", "build.sh"]

  timeline3:
    image: timeline
    container_name: timeline3
    expose:
      - "8080"
    entrypoint: ["/bin/bash", "build.sh"]